### ISSUE TITLE
Add psutil as requirement

### ISSUE THREAD

**Issue by ferazambuja** [njbbaer/unicorn-remote#7]
Cool project. It needs to add https://github.com/giampaolo/psutil as a requirement since the CPU update.
👍

**Comment by njbbaer** [comment]
Hi @ferazambuja, thanks for taking an interest in this project!

You're right, I forgot to add `psutil` to the `requirements.txt`. I can fix it, or if you're feeling adventurous you can make the change yourself and submit a pull request.

**Comment by njbbaer** [comment]
The `psutil` requirement has been added in PR #8 when switching over to the Pipfile format for managing dependencies.
